### ISSUE TITLE
firefox: await is only valid in async functions, async generators and modules

### ISSUE THREAD

**Issue by Lanchon** [Maxim-Mazurok/aliexpress-show-shipped-price#1]
hi,

the readme does not state which browsers are supported.

on firefox, this happens:
```
Uncaught SyntaxError: await is only valid in async functions, async generators and modules
[debugger eval code:22:31]
```

thanks for publishing this!

**Comment by Maxim-Mazurok** [comment]
Hey, I wrote it for Chrome, looks like firefox doesn't support top-level await, I have pushed a fix, and added note about browser support. Glad you found it useful, cheers!
